platform :ios, '10.0'

use_frameworks!

target 'Segment-Facebook_Example' do
  pod 'Segment-Facebook-App-Events', :path => '../'

  target 'Segment-Facebook_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
