platform :ios, '9.0'

target 'Segment-Facebook_Example' do
  pod 'Segment-Facebook-App-Events', :path => '../'

  target 'Segment-Facebook_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
