version: 2

jobs:
  build_and_test:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run: xcrun simctl list
      - run:
          name: Install build dependencies
          command: |
            sudo gem install xcpretty
            sudo gem install cocoapods -v 1.8.4

      - run: make install
      - run: make build
      - run: make test
      - run: make lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
